# This file contains the contents of the quiz questions which are asked by the 
# telegram bot, this is in the format of:
# ["A quiz question"]
# options = ["Things", "Which", "Show", "In the custom keybaord", "Secretly correct"]
# correct = "Secretly correct"
# Additionally at the start of the file there is the "winner" var which shows the message presented to the winner
winner = "Good job! Here is a cookie 🍪"
failed = "(•_•) I guess you made... ( •_•)>⌐■-■ the wrong choices... (⌐■_■)"

["What colour is the sky?"]
options = ["Blue", "Octarine", "Red", "Greige"]
correct = "Blue"

["Which of these are not a highly composite number?"]
options = [60, 72, 360, 720720]
correct = "72"

["In order for a chemical reaction to be thermodynamically favourable, the Gibbs free energy must be:"]
options = ["Irrelevant", "Negative", "Positive", "Zero"]
correct = "Negative"

["What shade of blue is superintelligent?"]
options = ["SmortBlue™", "Hoovooloo", "Bloo", "Ultramarine"]
correct = "Hoovooloo"

["Which Star Trek captain hails from France?"]
options = ["Sisko", "Kirk", "Pike", "Picard"]
correct = "Picard"

["Electrons are best described as:"]
options = ["Particles", "Wave functions", "A duality"]
correct = "A duality"

["What do priests chant when converting enemy units in Age of Empires?"]
options = ["Mandatum", "Stoma", "Wololo", "Bildembai"]
correct = "Wololo"

["At the time of destruction, what was the shield modulation of the Enterprise-D set to?"]
options = ["257.4", "48650.1", "Multiadaptive", "Anti-Klingon"]
correct = "257.4"

["What is the transition frequency between the two hyperfine ground states of caesium under ideal conditions?"]
options = [9_192_631_769, 9_192_631_770, 9_192_631_771, 9_192_631_772]
correct = "9192631770"

["On what message platform are you doing this quiz?"]
options = ["WhatsApp", "IRC", "Telegram", "Signal"]
correct = "Telegram"

# It seems Tolkien may have changed his mind on this?
# Interesting stuff: https://en.wikipedia.org/wiki/The_Two_Towers#Title_and_publication
["What are the names of the two towers refered to in 'The Lord of the Rings: The Two Towers'?"]
options = ["Orthanc and Minas Morgul", "Minas Tirith and Barad-dûr", "Helm's Deep and Minas Tirith", "Gotham and Metropolis"]
correct = "Orthanc and Minas Morgul"

# https://en.wikipedia.org/wiki/Deinonychus#Cultural_significance
["What is the name of the dinosaur from the film Jurassic Park described as a 'clever girl'"]
options = ["Deinonychus", "T-Rex", "Velociraptor", "Pantydraco"]
correct = "Deinonychus"

# https://www.imdb.com/title/tt8172158/characters/nm0790688
["Crowley didn't really fall, he:"]
options = ["Sauntered vaguely downwards", "Plummeted", "Tripped and recovered", "Soared upwards"]
correct = "Sauntered vaguely downwards"
